version: 2

models:
  - name: silver_claims
    description: "Cleaned and standardized healthcare claims data"
    columns:
      - name: charges
        description: "Insurance claim amount in USD"
        data_tests:
          - not_null
      - name: age
        description: "Patient age"
        data_tests:
          - not_null
      - name: bmi_category
        description: "BMI classification"
        data_tests:
          - not_null
          - accepted_values:
              values: ['underweight', 'normal', 'overweight', 'obese']
      - name: age_group
        description: "Age bucket"
        data_tests:
          - not_null
          - accepted_values:
              values: ['minor', 'young_adult', 'middle_aged', 'senior']